version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  unit-test:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - run:
          name: Running Terratest
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt update && sudo apt install terraform
            cd ./azure
            make units-tests

  validate-plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: "Check terraform code"
          command: |
            cd ./azure
            terraform init -input=false
            terraform validate
            terraform plan -out tfapply-azure
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run apply"
          command: |
            cd ./azure
            terraform apply tfapply-azure
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  plan-destroy:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Running Plan to Destroy"
          command: |
            cd ./azure
            terraform plan -destroy -out tfdestroy-azure
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  destroy:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Running Plan to Destroy"
          command: |
            cd ./azure
            terraform apply tfdestroy-azure
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  azure:
    jobs:
      - unit-test
      - validate-plan:
          requires:
            - unit-test
      - apply:
          requires:
            - validate-plan
      - hold-destroy:
          type: approval
          requires:
            - apply
      - plan-destroy:
          requires:
            - hold-destroy
      - destroy:
          requires:
            - plan-destroy

      
