version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  validate:
    working_directory: /tmp/project
    # executor: azure-cli/azure-docker
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      # - azure-cli/login-with-service-principal
      - run:
          name: "Check terraform code"
          command: |
            cd ./azure
            terraform init -input=false
            terraform validate
            terraform plan -out tfapply-azure

workflows:
  version: 2
  lint:
    jobs:
      - validate
